# Generated by Django 4.0.4 on 2022-08-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('select', models.CharField(choices=[('Fazendo', 'Fazendo'), ('Feito', 'Feito')], max_length=10)),
            ],
        ),
    ]
